# Site Info
title: Junmo's blog
tagline: 'for data science'
description: 'blog for data science'
url: http://jjmstars.github.io
logo: '/public/logo.png'
encoding: utf-8

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty
version: 1.0.0

# About/contact
author:
  name: jjmstars
  description: <strong>To be Great Data Scientist</strong></br> 같은 생각, 다른 행동
  gravatar: 58762ac605828c0ce5698045c3d54ccf # md5 hash of your email address
  contact:
    linkedin:  https://www.linkedin.com/in/junmo-jeong-144a91144/
    github:    https://www.github.com/jjmstars
    facebook:  https://www.facebook.com/junemo.jeong
    #twitter:  <hide>
    #weibo:    <hide>
    email:     mailto:jjmstars3@gmail.com
    instagram: https://www.instagram.com/jjmstars/

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
  Contents:           
    - '/blog/'
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }
  About:          
    - '/about/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image: https://jjmstars.github.io/public/skyline.jpg
  caption: Future is here. Fail big!
# Puglins
mathjax: true # whether support mathjax
google_analytics_token: 'UA-99892286-1' # leave blank if you don't want google analytics
#disqus_short_name: 'ratsgo-github-io' # leave blank if you don't want disqus

